---
- hosts: keycloak
  become: true
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - java8
    - keycloak
    - {role: 'monit', monit_checks: ['keycloak']}
  tasks:
  - name: Install Maven
    roles:
     - {role: 'maven' }
    tags: install-maven
